
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee_manager
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    port: 6379
    host: localhost
  mvc:
    view:
      prefix: /
      suffix: .html

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: chung.manager.entities
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 80
management:
  endpoints:
    web:
      exposure:
        include: health, beans

